postgres:
  name: postgres-deployment
  serviceName: db
  replicaCount: 
  image:
    name: postgres
    repository: postgres
    tag: "latest"
  username: "postgres"
  password: "postgres"
  port: 5432

redis:
  name: redis-deployment
  serviceName: redis
  replicaCount: 
  image:
    name: redis
    repository: redis
    tag: "latest"
  port: 6379

worker:
  name: worker-app-deployment
  replicaCount: 
  image:
    name: worker-app
    repository: kodekloud/examplevotingapp_worker
    tag: "v2"

resultApp:
  name: result-app-deployment
  serviceName: result-service
  replicaCount: 
  image:
    name: result-app
    repository: kodekloud/examplevotingapp_result
    tag: "v1"
  port: 80

votingApp:
  name: voting-app-deployment
  serviceName: voting-service
  replicaCount: 
  image:
    name: voting-app
    repository: kodekloud/examplevotingapp_vote
    tag: "v1"
  port: 80

appIngress:
  name: voting-app-ingress
  resultApp:
    url: result.webapp.com
    port: 80
  votingApp:
    url: voting.webapp.com
    port: 80