apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  labels: {{- include "voting-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector: {{- include "voting-app.postgres.labels" . | nindent 4 }}

    