apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  labels: {{- include "voting-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector: {{- include "voting-app.redis.labels" . | nindent 4 }}