apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resultApp.serviceName }}
  labels: {{- include "voting-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.resultApp.port }}
      targetPort: {{ .Values.resultApp.port }}
  selector: {{- include "voting-app.result.labels" . | nindent 4 }}