apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.votingApp.serviceName }}
  labels: {{- include "voting-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.votingApp.port }}
      targetPort: {{ .Values.votingApp.port }}
  selector: {{- include "voting-app.voting.labels" . | nindent 4 }}

    